---

- name: Ensure that a logstash user is exist
  user: name=logstash system=yes groups=adm
  notify: [ logstash restart ]

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [logstash, logstash-install]

- include: configure.yml
  tags: [logstash, logstash-configure]
